### ISSUE TITLE
Gamecube version crashes on boot

### ISSUE THREAD

**Issue by MethodOrMadness** [Mips96/Trogdor-Reburninated#1]
Game crashes instantly on hardware

Booted into swiss via GCLoader, loading from SD card in slot B, Trogdor-RB folder and dol on root of SD card in slot B
[Image here](https://imgur.com/a/c41rMCW)

**Comment by Mode8fx** [comment]
A functioning Gamecube build has (finally) been added, tested in Dolphin. I don't know how file I/O should work on Gamecube, so audio and save data do not work.
