### ISSUE TITLE
[3DS] CIA Format

### ISSUE THREAD

**Issue by korbosoft** [Mips96/Trogdor-Reburninated#2]
I was wondering if you could make a CIA of this for the 3DS. I have made a banner image and sound for this.
[Archive.zip](https://github.com/Mips96/Trogdor-Reburninated/files/12571654/Archive.zip)

**Comment by Mode8fx** [comment]
Done, it's added to the latest release. I swapped out the banner since there was something else I liked better, and I made a similar (but different) sound since that one wasn't working with bannertool, and I wanted to make the music part louder.

**Comment by korbosoft** [comment]
Nice!
