### ISSUE TITLE
Please add build instructions

### ISSUE THREAD

**Issue by mardy** [Mips96/Trogdor-Reburninated#6]
Hi! I'm trying to build the Wii SDL2 version. This change made me go a bit forward:

```diff
diff --git a/Trogdor-Reburninated/Makefile_wii_sdl2 b/Trogdor-Reburninated/Makefile_wii_sdl2
index 649230c..1f17538 100644
--- a/Trogdor-Reburninated/Makefile_wii_sdl2
+++ b/Trogdor-Reburninated/Makefile_wii_sdl2
@@ -109,7 +109,7 @@ export OUTPUT       :=      $(CURDIR)/$(TARGET)
 #---------------------------------------------------------------------------------
 $(BUILD):
        @[ -d $@ ] || mkdir -p $@
-       @$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile
+       @$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile_wii_sdl2
 
 #---------------------------------------------------------------------------------
 clean:
```
But then the build fails here:
```
$ make -j1 -f Makefile_wii_sdl2 V=1
demo.gba
bin2s -a 32 -H `(echo demo.gba | tr . _)`.h /home/mardy/src/git/gamedev/Trogdor-Reburninated/Trogdor-Reburninated/data/demo.gba > /tmp/tmp.AtrFGW9g39
powerpc-eabi-gcc -x assembler-with-cpp   -c /tmp/tmp.AtrFGW9g39 -o demo.gba.o
make[1]: *** No rule to make target 'demo_gba.h', needed by 'classes.o'.  Stop.
make: *** [Makefile_wii_sdl2:112: build_wii] Error 2
```
The `demo_gba.h` file is created in `build_wii`, but for some reason the Makefile does not see it?

**Comment by Mode8fx** [comment]
Yeah, I need to update the readme to point that out (or fix it). Just try building it, then when it fails after compiling demo_gba, try a second time and it’ll work.

**Comment by mardy** [comment]
> Yeah, I need to update the readme to point that out (or fix it). Just try building it, then when it fails after compiling demo_gba, try a second time and it’ll work.

Ah, I was running `make clean` everytime, that's why I didn't notice that it was so simple. :-) Thanks!

**Comment by Mode8fx** [comment]
No problem! I added a note to the Gamecube and Wii makefiles to dispel any further confusion on this.
