### ISSUE TITLE
won't install on 3ds

### ISSUE THREAD

**Issue by crow-man72** [Mips96/Trogdor-Reburninated#8]
tried installing this through universal updater and by putting files for the game onto my sd card, neither option will work

**Comment by crow-man72** [comment]
mabey this is just an issue with my 3ds, however, not sure

**Comment by jbbdude** [comment]
It's not you. I believe that Universal-DB is configured to look for the 3DS file in the newest release. The newest release doesn't have a 3DS version.

**Comment by Mode8fx** [comment]
> It's not you. I believe that Universal-DB is configured to look for the 3DS file in the newest release. The newest release doesn't have a 3DS version.

Oh, that's not good. Try it now; I added the previous 3DS v2.1 to the latest release.
